### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by sagiegurari** [orenbenkiki/loggy#1]
I see you have issues with the build, maybe a small suggestion, if you do want to run 5 last rust versions + tests + coverage including uploading it to codecov you could take a look at the following travis yml as an example:

https://github.com/sagiegurari/cargo-make/blob/master/.travis.yml

now, since you changed the coverage task to run tarpaulin, I'm not 100% sure that will work as is without any changes with codecov, so you might need to override that tarpaulin task in your makefile.toml to generate the output xml file, or just use kodcov.
hope it helps.

**Comment by orenbenkiki** [comment]
HI, thanks for noticing!

Actually my problems are with trying to run `cargo fmt` as part of a Travis
build. The README in `rustfmt` is flat-out wrong about it, and after some
investigation (all these failed builds you saw were intentional...), it
seems that currently it just isn't practical. There is an open issue to fix
it - see https://github.com/rust-lang-nursery/rustfmt/issues/2285 for
details, and feel free to chime in if you know of a workaround.

Thanks,

Oren Ben-Kiki

**Comment by sagiegurari** [comment]
I also issues with cargo format lately. not sure why they did the change they did.
anyhow, I updated cargo-make few days ago due to that.
you now run format with --force to make it work as nightly only works on rust nightly.
again, not sure why they made it so complex :(

these come from cargo-make default tasks, maybe it will help you.
so just run always the old format with --force

````toml
[tasks.format-stable]
description = "Runs the cargo rustfmt plugin."
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--write-mode=overwrite", "--force"]

[tasks.format-nightly]
description = "Runs the cargo rustfmt nightly plugin."
install_crate = "rustfmt-nightly"
command = "cargo"
args = ["fmt", "--", "--write-mode=overwrite"]

[tasks.format]
description = "Runs the cargo rustfmt plugin."
alias = "format-stable"
````
